
["global options"]
	#turns the burn mechanic on or off
	burntOn = true
	#fires go out when it's raining
	rainExtinguish = true
	#vanilla fire can trigger the burn
	vanillaBurn = true
	#lava can trigger the burn
	lavaBurn = false
	#lightning strikes can trigger the burn
	lightningBurn = true
	#hot/dry/cold/wet biomes affect the burn speed and spread
	biomeSpecific = true

["burn settings"]
	#(0-100) how quickly the burn spreads from one block to another
	burnSpread = 40.0
	#% chance of fire spreading across grass/moss
	groundSpread = 60.0
	#(0-100) how quickly a smoldering block becomes burnt
	burnSpeed = 20.0
	#distance from a player the burn remains active
	playerDistance = 256.0
	#flame enchanted bow can set fires
	flameBow = true
	#fire aspect enchanted tools can set fires
	fireAspect = false
	#Burnt's fire can deal damage
	burnDamage = true

["block settings"]
	#non-natural blocks can burn
	craftedBlocksBurn = true
	# wooden barrels and their contents can burn
	burnBarrels = true
	#wool can burn
	woolBurn = true
	#some blocks adjacent to fire become sooty blocks
	soot = true
	#terracotta adjacent to fire can become cracked
	crackTerracotta = true

["recovery settings"]
	#burnt grass can grow back
	grassRecovery = true
	#% chance of grass recovering on random world tick
	grassRecoverSpeed = 20.0
	#allow logs to break down and trees to replant themselves
	forestRecovery = true

["Visual Effects"]
	#blocks can randomly fall during the burn
	randomCollapses = true
	#% chance of collapse over time
	collapseChance = 20.0
	#smoke particles on/off
	smokeParticles = true
	#flame particles on/off
	flameParticles = true
	#ash particles on/off
	ashParticles = true
	#ground smoke particles on/off
	groundSmoke = true
	#distant smoke particles on/off
	distantSmoke = true

