
[movement]
	#Allowed Values: ALLOW, STOP_SPRINTING, DISABLED
	shootWhileSprinting = "STOP_SPRINTING"
	sprintWhileReloading = true
	reloadWhileShooting = true
	#Default: 25.0
	#Range: 0.0 ~ 90.0
	crawlPitchUpperLimit = 50.0
	#Default: -10.0
	#Range: -90.0 ~ 0.0
	crawlPitchLowerLimit = -90.0
	dynamicCrawlPitchLimit = true
	allowUnload = true

[misc]
	crawlVisualTweak = true
	#For better compatibility
	disableTaCZCrawl = true
	vsCollisionCompat = false
	vsExplosionCompat = false
	firstAidCompat = true

